version: '3.8'

services:
  app:
    container_name: sooft_app
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/api
      - /api/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=project
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword123!
    restart: unless-stopped
    depends_on:
      - db

  db:
    container_name: sooft_db
    image: mysql:9.2.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123!
      MYSQL_DATABASE: project
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword123!
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
